services:
  nginx:
    container_name: nginx
    network_mode: "host"
    build:
      context: .
    volumes:
      - ./entrypoint-init.d:/docker-entrypoint-init.d
      - ./conf.d:/etc/nginx/conf.d
      - /etc/letsencrypt/live/example.com/fullchain.pem:/etc/nginx/certs/default.crt
      - /etc/letsencrypt/live/example.com/privkey.pem:/etc/nginx/certs/default.key
    restart: unless-stopped
    env_file:
      - /etc/default/nginx

  redis:
    container_name: redis
    image: "redis:alpine"
    network_mode: "host"
    restart: unless-stopped
    env_file:
      - /etc/default/redis

  postgres:
    container_name: postgres
    image: "postgres:alpine"
    network_mode: "host"
    volumes:
      - /var/lib/postgresql/data:/var/lib/postgresql/data
    restart: unless-stopped
    env_file:
      - /etc/default/postgres

  chroma:
    container_name: chroma
    image: ghcr.io/chroma-core/chroma:latest
    network_mode: "host"
    volumes:
      - /var/lib/chroma/data:/chroma/chroma
    restart: unless-stopped
    env_file:
      - /etc/default/chroma
